# Generated by Django 5.2.6 on 2025-09-06 13:07

import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models

import ai.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StructuredInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "sentiment",
                    django_enumfield.db.fields.EnumField(
                        blank=True, enum=ai.enums.Sentiment, null=True
                    ),
                ),
                ("topics", models.JSONField(blank=True, null=True)),
                ("keywords", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
